# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if .Values.nginx.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $name := include "ditto.name" . -}}
{{- $labels := include "ditto.labels" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-nginx-config-nginx-htpasswd
  labels:
    app.kubernetes.io/name: {{ $name }}-nginx-config
{{ $labels | indent 4 }}
data:
  "nginx.htpasswd": |-
{{ range $key, $value := .Values.global.basicAuthUsers }}
{{ (htpasswd $value.user $value.password) | indent 4 }}
{{- end -}}

---
{{- end -}}
